### ISSUE TITLE
Doctrine Bidirectional Relationship Copying

### ISSUE THREAD

**Issue by Toasterson** [myclabs/DeepCopy#10]
Hi

I have two entities with a BIDirectional Relationship, Timeslices and Activities.
Timeslice has an Ativity and Activity has multiple Timeslices.
When i Copy a Timeslice i want to keep the Reference to Activity. I Use a KeepFilter for that which Keeps the Activity but does not update the Timeslices Field in Activity. Doctrine thus looses the Relationship.

If I remove the KeepFilter It tries to make a new Activity which isnt desired either.
Have you encountered this Situation before?

**Comment by mnapoli** [comment]
> but does not update the Timeslices Field in Activity

Yes that's intended, the clone should replace magically the original object where the original object was referenced.

I think it's something you need to handle yourself because it's not a generic behavior. Likewise you might want to add the new object to the collection, or replace the original one. It's not so obvious what should happen and depends on your use case.

**Comment by ProPheT777** [comment]
You can achieve this by creating a Filter who called setter instead of pass value by reference. In that way just implement the sync logic in your setter method. You can use the symfony propertyAccess component to do it in the most easy way if you do not have dependencies constraints (http://symfony.com/doc/current/components/property_access/introduction.html).

E.g (take from the first blog post about it I found, (full here : http://culttt.com/2014/07/21/working-relationships-doctrine-2) : 

```php
/**
 * Add the user to a Cribbb
 *
 * @param Cribbb $cribbb
 * @return void
 */
public function addToCribbb(Cribbb $cribbb)
{
  $cribbb->addUser($this);
 
  $this->cribbbs[] = $cribbb;
}
```
