### ISSUE TITLE
Breaking change in patch release?

### ISSUE THREAD

**Issue by alexander-akait** [myclabs/DeepCopy#138]
`v1.9.1` require php 7.1
`v1.9.2` reqiure php 7.2

It is violate semver police, i can't find own sermver file what describe why this changes can be doe in patch version (good practice if you can brake something in patch or minor versions)

**Comment by theofidry** [comment]
It looks like I tagged the wrong branch, fixed in 1.9.3.

Note however that changing require versions or package versions _is_ semver compliant. You didn't find a semver entry describing it because they don't forbid anything there. The reasoning is: if you were to upgrade and it breaks your code, it would not be semver compliant. However a dependency requirement change only affects your ability to update: if you can it won't break the code, if you cannot well you just can't install that version, but it's not gonna break your code.

In any case, thanks for the report :)

**Comment by mnapoli** [comment]
> Note however that changing require versions or package versions is semver compliant.

:+1:
