### ISSUE TITLE
Please add tests in the release tarball

### ISSUE THREAD

**Issue by GuillaumeSeren** [myclabs/DeepCopy#58]
Hey, 🎄 
I am packaging DeepCopy on gentoo, to have a complete phpunit, source-only, in our tree,
I noticed that the tests are not in the tarball, maybe I missed something,
I have packaged composer (and all dependencies) and it is not so common for upstreams,
to have tests only in the git tree.

Is there a way that the tests can be in the tarball in the next release ?

**Comment by mnapoli** [comment]
Hi! Indeed tests are not shipped, it makes releases a bit lighter and avoids sending [random stuff like this](https://github.com/sebastianbergmann/phpunit/blob/9758eee6421efd997a42fe850f74292a490e9c70/src/Util/PHP/eval-stdin.php) on everyone's servers (some applications like Drupal deploy the `vendor/` directory). Tests are run on CI anyway (Travis, on each commit) and running tests of the dependencies are such a rare use case that users who want to do that have to download the source.

**Comment by GuillaumeSeren** [comment]
@mnapoli Hey thanks for the reply, ☃️ 
well I understand your point, but having the test in each release is really convenient, if you want to run the test of your application, phpunit, symfony, laravel do it, and it is really common.
I am just a user, and it would be neat to have them, thank you for reading !

**Comment by theofidry** [comment]
That's a bit of an old issue, but I think it shouldn't be a problem to exclude the tests. There is little usefulness to do so and the only caveat is that it may require us to be more careful about what we don't want to send. Otherwise the benefit is that pulling the package requires less space.

Symfony, Laravel & co don't do it because they didn't really care until now cf. https://github.com/symfony/symfony/issues/22064

I personally don't feel strongly about either approach, but as there is no consensus I won't change it.

**Comment by GuillaumeSeren** [comment]
Hey thank you for taking the time to write your opinion 🍺 

I understand and respect your choice,
I just think that it could be useful to have a complete release tarball in addition to your 'production' release.
